import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import qaMost from '../public/qa-most-fave'
import qaLeast from '../public/qa-least-fave'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jennifer Tran - Vercel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Vercel Take Home Test
        </h1>

        <p className={styles.description}>
          Answers submitted by Jennifer Tran.
        </p>

        <h2>1) From this list, rank your 5 most favourite and 5 least favourite tasks. Please provide reasons why each task is your most or least favourite</h2>
        <>
        <h3>Most favorite tasks (1st rank being the most favorite)</h3>
          {Object.values(qaMost).map((q, index)=>{
            return (
              <div className={styles.card}>
                <h4>{ `${index + 1}. ${q.task}` }</h4>
                <ul>
                  { Object.values(q.reason).map((reason) => {
                    return (
                      <li>{ reason }</li>
                    )
                  })}
                </ul>
              </div>
            )
          })}

          <h3>Least favorite tasks (5th rank being the least favorite)</h3>
            {Object.values(qaLeast).map((q, index)=>{
              return (
                <div className={styles.card}>
                  <h4>{ `${index + 1}. ${q.task}` }</h4>
                  <ul>
                    { Object.values(q.reason).map((reason, index) => {
                      return (
                        <li>{ reason }</li>
                      )
                    })}
                  </ul>
                </div>
              )
            })}
        </>

        <h2>2) What do you want to learn, or do more of, at work?</h2>

        <div className={styles.card}>
          <ul>
            <li>Work with front end frameworks and serverless functions</li>
            <li>Build familiarity with Vercel platform features and common runtime errors</li>
            <li>Specialize in a few product areas</li>
            <li>Learn more on identifying/diagnosing network  and latency issues</li>
            <li>Update docs on the fly (without a rigorous process, making it easier to contribute)</li>
            <li>Contribute to process improvements</li>
          </ul>
        </div>

        <h2>3) Which technical article, guide or lightning talk left the biggest positive impression on you? Why? Ideally, this article would not be associated with Vercel or web development, by the way! Please provide links.</h2>

        <div className={styles.card}>
          <ul>
            <li>Disclaimer: Response not meant to be political! It’s what captured me upon first discovery/impression</li>
            <li>Link: <a href="https://2020.yang2020.com/policies/the-freedom-dividend/">https://2020.yang2020.com/policies/the-freedom-dividend/</a></li>
            <li>Why: When scrolling through social media in 2019, I stumbled upon a non-profit US presidential candidate. Initially, what captured me was the modern social media marketing and website’s UI. Proceeding forward to explore, I read through his most popular policy: The Freedom Dividend. I was impressed with the flow of the policy proposal:</li>
            <li>First, the proposal and its conditions were clearly defined</li>
            <li>The problems to be solved varied and were highlighted</li>
            <li>Excerpts were shared on who also championed for the idea</li>
            <li>Goals were outlined to cover more than just one perspective</li>
            <li>An action item was highlighted to summarize what he’s committing to </li>
            <li>Excerpts from historical events and figures displayed to reference how the policy is becoming more relevant based on current trends</li>
            <li>There’s an overall neutral tone to the policy (doesn’t speak negatively towards others, but instead, focuses on solving the problems)</li>
          </ul>
        </div>

        <h2>4) Add a temporary in-app redirect to your project, redirecting /hello-vercel (or any path – but be sure to tell us which!) to https://vercel.com</h2>

        <div className={styles.card}>
        <p>Done! Here&apos;s the path which temporarily redirects to vercel.com: <a href="/hello-vercel">https://vercel.com/hello-vercel</a></p>
        </div>

        <h2>5) A customer writes in to the Helpdesk asking &quot;How do I do a redirect from /hello-vercel to https://vercel.com?&quot; In a couple of paragraphs, how do you respond?</h2>
        <div className={styles.card}>
          <p>Hi Scott,</p>
          <br/>
          <p>My name is Jennifer, and I’ll be happy to assist with your inquiry.</p>
          <ul>
            <li>If you&apos;re using Next.js Redirects, you can use the redirects property in a next.config.js file.</li>
            <li>For other Redirects, you can use the redirects properties a vercel.json file.</li>
          </ul>
          <p>Here&apos;s an article with more information: <a href="https://vercel.com/support/articles/does-vercel-support-permanent-redirects#in-application-redirects">https://vercel.com/support/articles/does-vercel-support-permanent-redirects#in-application-redirects</a></p>
          <br/>
          <p>Let me know if you&apos;ve any questions or if this addresses your inquiry.</p>
          <br/>
          <p>Kind Regards,
            <br/>Jennifer Tran
          </p>
        </div>

        <h2>6) A customer writes in to the Helpdesk stating &quot;I have a custom domain which I purchased at GoDaddy and I want to use it on my project&quot;. In a couple of paragraphs, how do you respond?</h2>
        <div className={styles.card}>
          <p>Hi Scott,</p>
          <br/>
          <p>My name is Jennifer, and I’ll be happy to assist with your inquiry.</p>
          <br/>
          <p>Here’s an article covering steps on how to add a custom domain to your project: <a href="https://vercel.com/docs/concepts/projects/custom-domains#adding-a-domain">https://vercel.com/docs/concepts/projects/custom-domains#adding-a-domain</a></p>
          <br/>
          <p>Let me know if you’ve any questions around this topic or if this addresses your inquiry.</p>
          <br/>
          <p>Kind Regards,
            <br/>Jennifer Tran
          </p>
        </div>

        <h2>7) What do you think is one of the most common problems which customers ask Vercel for help with? How would you help customers to overcome common problems, short-term and long-term?</h2>
        <div className={styles.card}>
        <ul>
          <li>Common problems: Caching, DNS, and historical data or logging</li>
          <li>Short-term: Update FAQs, provide examples in docs, or create articles/guides</li>
          <li>Long-term: Share common reported problems to Product manager to consider feature enhancement for a more intuitive user experience</li>
        </ul>
        </div>

        <h2>8) How could we improve or alter this familiarisation exercise?</h2>
        <div className={styles.card}>
        <p>I like the creative aspect of question 3, and an improvement could be to rephrase it so it’s more open - it first asks for technical article, guide or lightning talk (all commonly used in tech industry), but later on states it ideally shouldn’t be related to web development or Vercel (had to reframe my thoughts after reading it a few times).</p>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
